[Unit]
Description="Left 4 Dead 2 Survival Server"

[Container]
ContainerName=left4dead2-survival-server
Image=localhost/l4d2-gameserver:v1.0
Volume=$HOME/game:$HOMEDIR/l4d2
Port=27015:27015

[Service]
Restart=always

[Install]
WantedBy=default.target


